### ISSUE TITLE
pip install does not find requirements.txt 

### ISSUE THREAD

**Issue by ldpgh** [SimLeek/cv_pubsubs#9]
python -m pip install CVPubSubs
```
Collecting CVPubSubs
  Downloading https://files.pythonhosted.org/packages/93/49/d82e1eba5b46ead6d41e027e035cda4506a02f77e74efbe7b353fec25494/CVPubSubs-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\.....\appdata\local\temp\pip-install-dgz2el\CVPubSubs\setup.py", line 16, in <module>
        with open('requirements.txt', 'r', encoding='utf-8') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\.......\appdata\local\temp\pip-install-dgz2el\CVPubSubs\
```

pip install git+https://github.com/SimLeek/cv_pubsubs.git
```
Collecting git+https://github.com/SimLeek/cv_pubsubs.git
  Cloning https://github.com/SimLeek/cv_pubsubs.git to c:\users\........\appdata\local\temp\pip-req-build-qc0orl
  Installing build dependencies ... done
Requirement already satisfied: numpy in c:\.................\python\python2.7.12\lib\site-packages (from CVPubSubs==0.3.3) (1.11.2)
Collecting opencv_python (from CVPubSubs==0.3.3)
  Downloading https://files.pythonhosted.org/packages/20/c6/d485410491070e66d5954b28d79d10bd3026ad04001fc77e921509edb5af/opencv_python-4.0.0.21-cp27-cp27m-win32.whl (22.1MB)
    100% |################################| 22.1MB 142kB/s
Collecting localpubsub==0.0.1 (from CVPubSubs==0.3.3)
  Downloading https://files.pythonhosted.org/packages/36/f6/465c799ad52be79e3c2024e01f4690aa3a22421f1af598340aaf8264d417/localpubsub-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\........\appdata\local\temp\pip-install-bjkuh2\localpubsub\setup.py", line 16, in <module>
        with open('requirements.txt', 'r', encoding='utf-8') as f:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\.........\appdata\local\temp\pip-install-bjkuh2\localpubsub\
```

It seems the delivered package-files from   `https://files.pythonhosted.org`   do not contain the `requirement.txt` file.

**Comment by SimLeek** [comment]
Interesting. This definitely needs to be fixed.

**Comment by SimLeek** [comment]
For now @ldpgh , use `pip install cvpubsubs` if you can.

**Comment by SimLeek** [comment]
Whew... done. I'm glad there python wheel integration testing. Now I don't have to worry about this popping up again.
